### ISSUE TITLE
Android Chrome camera.undefined_map_data 

### ISSUE THREAD

**Issue by mafrosis** [TheLastProject/lovelace-valetudo-map-card#118]
Hi, sorry for opening yet another issue with the card not working 😄 . It *works* for me on desktop Chrome on macOS, but does not work on Android Chrome (!)

This card was working on both devices when I was on version `v2021.12.05`

I have:

* Followed the release note steps
* Cleared my cache many times
* Deleted entities and restarted HA
* Toggled off MQTT in valetudo, cleared all MQTT data, toggled on MQTT
* My vacuum entity is now called `vacuum.valetudo_rockrobo`

![Screenshot_20220303-163914](https://user-images.githubusercontent.com/243851/156504407-b8579f6b-53b2-47b4-8219-3744b3df143a.png)
<img width="435" alt="Screen Shot 2022-03-03 at 16 48 46" src="https://user-images.githubusercontent.com/243851/156504458-e0280c0d-0856-4838-9b7c-816ecdaf47cb.png">

**Comment by TheLastProject** [comment]
It really sounds like your Android Chrome is caching an old version of the card. I don't use Chrome so I don't know if it has a dedicated way to really clear the cache more reliably on Android because it really doesn't seem cleared.

Or your desktop is using the old version and you didn't read the release notes and thus your config is incorrect for the new version.

**Comment by TheLastProject** [comment]
Probably the last one actually, given `undefined_map_data`.

**Comment by mafrosis** [comment]
Hmm. Clearing caches is a nuisance I've been fortunate to ignore in last 10 years or so since I did web dev 😎 

How does `undefined_map_data` indicate I didn't read release notes properly? ie, which step would fix that? As I wrote above, I did the MQTT dance to refresh the data, and I got a new `entity_id` to boot.

Can I be more surgical with the "cache clear"? Like, what exactly is stale here... A cached JS file? A cookie? Some webstorage?

**Comment by TheLastProject** [comment]
It implies the new vacuum option isn't set, causing it to use the value `undefined`: https://github.com/TheLastProject/lovelace-valetudo-map-card/releases/tag/v2022.01.0

The caching is probably a stale JS file yeah.

**Comment by mafrosis** [comment]
I updated the card to the new `vacuum.` entity, and it works on desktop browser, so config must be right.

It must be caching on the Android device, which, when I clear the cache, is clearly not clearing the cache.

**Comment by mafrosis** [comment]
I installed a new browser (DuckDuckGo) which I've never used before. Same issue. Can you consider how it's possible to work on one client and not on another? Thanks.
![Screenshot_20220305-160806](https://user-images.githubusercontent.com/243851/156869314-3a1ee0e3-99a2-4bdc-8ec0-1dd415ec0c7e.jpg)

**Comment by TheLastProject** [comment]
What is your card's config?

**Comment by Ricetato** [comment]
Hi, I just thought I'd chime in that I am also experiencing this "Entity not available: camera.undefined_map_data" issue since today. I've tried clearing local storage/cache/cookies for my HA domain on desktop (Edge), swapped to private browsing, my mobile (Android HA app) and also a laptop (also Edge). I've got a few more devices I could chuck at this but don't think that's going to make a difference. I've tried removing the plugin entirely and re-installing, removed the MQTT integration & re-adding it, and rolling back to Nov version of the card didn't seem to do anything so suspect something else might've broke it. 

This morning I did decide to swap to the 64bit image for my RPi so moved the config over and installed Mosquitto in a container (wasn't an official 32bit image), there wasn't any issues after this process though. I also hit update on HACS and a few other frontend extensions around the same time before I noticed it. The other Frontend extensions I updated are:
- Google Dark Theme
- button-card
- Stack In Card
- auto-entities

I tried uninstalling each extension individually (removed an extension, restart server, re-install and repeat for each extension). No change for any extension.

@mafrosis do you have any overlap in changes?

Here's my config for the card if it helps at all, it's embedded within a vertical stack card but I get same the error regardless of if its in the stack.
`type: custom:valetudo-map-card
entity: camera.map_data
vacuum_entity: vacuum.dreame_f9
title: null
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 160`

**Comment by TheLastProject** [comment]
@Ricetato Your config is obviously wrong. Please read: https://github.com/TheLastProject/lovelace-valetudo-map-card/issues/118#issuecomment-1057749277

**Comment by Ricetato** [comment]
Ah yeah.. just typical case of the user being a dunce, didn't RTFM 🤦‍♂️

Cheers @TheLastProject!

**Comment by mafrosis** [comment]
Turns out that the Android device was showing the correct error, and the desktop was working because I hadn't updated my `ui-lovelace.yaml` to use `vacuum: ` and not `entity_id: `.

Factors that got me into this mess (which took a couple hours of tinkering to unpick):

- I failed to delete `Roborock` under `homeassistant/camera` when following the release notes. Manually deleting a bunch of nodes in MQTT is an error prone process - even for an experienced engineer 😅 
- I misunderstood the release note which says "Edit your map card and set the new vacuum option." - I updated the card to use the new `entity_id`, not replace `entity_id` & `vacuum_entity` with just `vacuum`. I had to find that in the README. I guess related to #110, I find it odd that this card doesn't use `entity_id` as an option, when every single other card does. That quirk is at least part of the reason I had it set up wrong.

Thanks for your help, and you were right indeed - another case of user error. Perhaps with so many user errors coming up over this issue, the release notes for breaking changes need to be more detailed? 🤷 

Whatever the lesson is, if we didn't like hacking around debugging this kind of thing from time to time then we wouldn't be using HA in the first place!!
