### ISSUE TITLE
How configure valetudo-map-floor-color?

### ISSUE THREAD

**Issue by ricain59** [TheLastProject/lovelace-valetudo-map-card#30]
Hi,

i'm try used this --valetudo-map-floor-color and --secondary-background-color without success on lovelace.. :(
Can you share an exemple please?

Thank you.

**Comment by TheLastProject** [comment]
Those are the default values, not the settings to change. You need to use the option "Name" in the table to see what to change.

Example:
```
type: 'custom:valetudo-map-card'
entity: sensor.xiaomi_map
floor_color: green
```

**Comment by ricain59** [comment]
Hi,

Thank you for answer. 
I've try and work your exemple, but --secondary-background-color and --valetudo-map-floor-color is not used? for color background? In my exemple i want paint white background.

![image](https://user-images.githubusercontent.com/13002652/74941322-bad20480-53ea-11ea-9e1c-2f3d6741ed63.png)

**Comment by TheLastProject** [comment]
`--valetudo-map-floor-color` and `--secondary-background-color` are [CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), so that it allows people who create Home Assistant themes to set default colours. So, you would only change this in a custom Home Assistant theme.

As an end user, you just use the names and give it a value in the card configuration. In your case:
```
type: 'custom:valetudo-map-card'
entity: sensor.xiaomi_map
floor_color: white
```

**Comment by ricain59** [comment]
Ok, thank you.
