### ISSUE TITLE
Please add an option to have no title in the map card

### ISSUE THREAD

**Issue by Doa132** [TheLastProject/lovelace-valetudo-map-card#40]
Just updated the map card via HACs and now my button is messed up because the title (even if set blank) pushes the map down and makes it smaller. In this button, the map is supposed to be the entire right side of the button, in line with the vacuum icon.
<img width="253" alt="Screen Shot 2020-05-03 at 02 11 10" src="https://user-images.githubusercontent.com/43628930/80869361-5f25d080-8ce3-11ea-8538-e7ed0086d436.png">

**Comment by TheLastProject** [comment]
Oh that's an interesting way to use the map card. Yeah, I can understand how I broke that.

**Comment by Doa132** [comment]
Thanks. Valetudo map card really is a great card. One of the only 2 non-Button Cards I use on my main view. Everything else is just various forms of the Button Card nested within stacking cards.

**Comment by TheLastProject** [comment]
It's really cool to see the different ways people use my code, especially seeing things like this that I hadn't thought of before. I'm very glad you like my card :)

Anyway, your issue should be fixed in 86653f08a77742d3c92bb779999b31f55eb4ead3. Just set title to an empty value:
```
type: 'custom:valetudo-map-card'
title: ""
```

Thanks for the report!

**Comment by Doa132** [comment]
Thanks for the quick fix!
