### ISSUE TITLE
Virtual wall width set to 0 still draws the line

### ISSUE THREAD

**Issue by XtracT** [TheLastProject/lovelace-valetudo-map-card#42]
Hello!

First of all, thank you for your amazing card. Now that summer is arriving I have set up a virtual wall in the balcony door, but it shows up in the map. I thought that setting "virtual_wall_width" to zero would do the trick, but it does not. 

I have modified your code and now it does not draw it, but I think you won't like my solution so I better suggest it here!

Thanks!

/Xtract

**Comment by TheLastProject** [comment]
Thank you for your report and the kind words :)

It appears the bug is here: https://github.com/TheLastProject/lovelace-valetudo-map-card/blob/master/valetudo-map-card.js#L194

My idea was to set it to 1 if it wasn't defined, but obviously, 0 is also a falsey value so will also set the value to one. Not that that would've directly mattered, because looking at https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth it is stated that "Zero, negative, Infinity, and NaN values are ignored".

I have fixed this in 97c745f by not drawing the path or virtual walls if the width settings were explicitly set to 0 and also added a show_virtual_walls setting for consistency (as show_path exists). Setting this to false has the same effect as setting the width to 0.

While looking into this I noticed it's impossible to hide no_go_areas and obstacles too, so I added support for hiding those in 9e4017e before someone asks :)
