### ISSUE TITLE
Custom element doesn't exist: valetudo-map-card.

### ISSUE THREAD

**Issue by Dinth** [TheLastProject/lovelace-valetudo-map-card#68]
I have installed the frontend addon using HACS, but (even after restarting HA), when im trying  to add the card as per documentation, im getting this error:

Custom element doesn't exist: valetudo-map-card.

![Screenshot from 2020-08-18 13-48-22](https://user-images.githubusercontent.com/313674/90514763-8486ff00-e159-11ea-9f40-9b87ee02335b.png)

**Comment by TheLastProject** [comment]
Have you tried doing a hard refresh in your browser? Home Assistant loves to cache things too long sometimes.

Also, anything in your browser console? https://kb.mailster.co/how-can-i-open-the-browsers-console/

**Comment by Dinth** [comment]
Thanks, it was indeed a cache problem.

**Comment by theorician** [comment]
@TheLastProject I'm seeing this error currently as well. It works fine in Firefox, but it does not load in the Home Assistant Android App. I assume it's also a caching problem as I've seen talk on Reddit that it "just starts working sometime." 

Is there something we can actually do to fix this issue? There's this issue from HA-Frontend: https://github.com/home-assistant/frontend/issues/7384 that's related I think.

**Comment by TheLastProject** [comment]
I don't know of anything that can be done except clearing your cache or reloading until you get the new version. I also think the comment by @iantrich "This is an issue the card must address" on https://github.com/home-assistant/frontend/issues/7384#issuecomment-711469681 makes little sense, because I would think it is Home Assistant's responsibility to deal with caching and also... how would the card even be able to fix anything if it's not loaded? Code that isn't loaded can't run to fix it not being loaded after all...

I do know that HACS nowadays after adding or updating a custom component offers to clear the cache so maybe HACS could be made smarter to keep track of other browsers and offer clearing the cache if they don't have it yet.

Anyway, I see no way for me to be able to fix it as, well, my code isn't loaded due to cache issues. And I can't fix a browser not loading my code with more code that won't be loaded.

**Comment by iantrich** [comment]
My comment was not in regards to caching, but rather in reference to handling lazy loading of more-info elements which I do not believe is an issue you are facing.

**Comment by TheLastProject** [comment]
Ah, thanks for explaining. No, that's not relevant then.
