### ISSUE TITLE
No sensor appear in 2020.12

### ISSUE THREAD

**Issue by exotsk** [TheLastProject/lovelace-valetudo-map-card#77]
After installin over  latest HACS (2020.12 support only) not appear sensor "xiaomi_map". All setiings ios ok, no error in logs. Anyone have the same?

**Comment by TheLastProject** [comment]
I updated to Home Assistant 2020.12.1 myself today and it still works. 

If you go to Configuration -> Entities and search for "xiaomi_map", do you have any result? If you click it and then click the settings icon, does it look something like this?

**Comment by CodeFinder2** [comment]
Hi,

not sure if its a similar bug but I can see a sensor but this sensor only contains "OK" and no map data:
![image](https://user-images.githubusercontent.com/20599588/102943008-27a8a600-44b7-11eb-8d08-784f6038bff0.png)

What's wrong here? (I can also open another issue. ;-) )

**Comment by TheLastProject** [comment]
@CodeFinder2 You're not actually using Valetudo, but Valetudo RE, an unofficial fork which I removed support for due to them stealing code without keeping attribution in place (which is literally the only thing you HAVE to do under Valetudo's license). As the README says:

>Valetudo can be found on https://github.com/Hypfer/Valetudo. This is the only version of Valetudo we officially support.

**Comment by TheLastProject** [comment]
@exotsk Do you have any more info? Or I'll close this issue soon for no response to keep the issue tracker clean (but you're free to reopen once you have more info)

**Comment by CodeFinder2** [comment]
@TheLastProject thanks for your quick response! 🙂

I know I was using valetudo RE and thought / hoped that this isn't a problem (and supported as well). I switched from valetudo to valetudo RE  because (at least at that time) it had some useful features which valetudo didn't have.

I was surprised to read that valetudo RE was "stealing code without keeping attribution". 😱

The first sentence on valetudo RE's github page says "This is a fork of Valetudo by Hypfer, created by me [...]". Also in the about section of valetudo RE's web interface, it is stated:
![Screenshot_20201223-133628__01](https://user-images.githubusercontent.com/20599588/102996916-3a0cf900-4524-11eb-9f0c-20e50b2fef53.jpg)

I totally respect your decision to drop support for it but would also be very grateful if you would consider adding it back to your implementation, considering the attribution I quoted above. Thank you! 😊

**Comment by exotsk** [comment]
This problem occurs when recording the B sensor configuration configuration.yaml. But after I made a record in the config following the path that is listed in the configuration.yaml sensor appeared.

**Comment by TheLastProject** [comment]
@CodeFinder2 You may notice that if you look at that contributor graph I'm not in there. Even though https://github.com/Hypfer/Valetudo/pull/496 clearly exists in Valetudo RE too. Why? Because rand256 copied my code without keeping the git copyright info in place. They have done this multiple times but completely ignored me in the Valetudo chat when I told them that's not cool.

@exotsk Sorry for the late response. Sounds like you got it working? I'll close this now then. Feel free to reopen if I misunderstood you.
