### ISSUE TITLE
Entity not available: camera.map

### ISSUE THREAD

**Issue by LeChuck2909** [TheLastProject/lovelace-valetudo-map-card#85]
I updated Valetudo to Firmware: `2021.02.0` and the lovelace-valetudo-map-card to `v2021-02-20`.

I have mqtt discovery enabled and the device was created with all the entities, as it should be. also the new entity is present:

![image](https://user-images.githubusercontent.com/61522664/109476372-25466780-7a77-11eb-80ef-61c09a06e1d6.png)

When i add a new card according your expample, it says: `Entity not available: camera.map`

![image](https://user-images.githubusercontent.com/61522664/109476548-57f06000-7a77-11eb-9dde-b53f007aadf8.png)

Before i updated both, i was successfully using this card with the former valetudo firmware.

Thanks.

**Comment by TheLastProject** [comment]
Can you click the map entity in your first screenshot to see what entity name it actually has?

**Comment by LeChuck2909** [comment]
![image](https://user-images.githubusercontent.com/61522664/109496530-1076cd80-7a91-11eb-9a82-e86045ee874f.png)

**Comment by TheLastProject** [comment]
That is weird, it should work. Are you sure there is no browser cache or anything? Home Assistant likes to cache very very aggressively

**Comment by LeChuck2909** [comment]
ok, wow it was a cache issue. the interesting thing: i tried to refresh with `Control + Shift + R` which didnt help. after your suggestion i hit `F12` > `Chrome Developer Tools` > `Application` tab > `Clear storage` in left tree. Now it works. thank you.

**Comment by cmccambridge** [comment]
Just stopping by to say thank you - cache reset was my issue as well when I migrated to Valetudo 2021.02.0 and the new map card and then saw the same `Entity not available:` warning on my iOS app. Refreshing the cache sorted me out.

For anyone else on iOS: Open the `App Configuration` sidebar section, then `Reset frontend cache` at the very bottom.

**Comment by CodeFinder2** [comment]
Just want to add that I was successful in getting rid of this error by deleting all topics/data on `homeassistant/vacuum`, `homeassistant/camera`, `valetudo` and `robot` via the "MQTT Explorer" tool and then disabling and re-enabling the "MQTT Connectivity" in the vacuum. I also tried to delete entities in HA but that wasn't possible for all. It's possible that I had old remaining enitites for whatever reasons (maybe due to updating the vacuum). After fixing the correct value for `vacuum` (in my case: `vacuum: valetudo_imaginaryunwrittenworm`), it works again.

Hopefully, this helps someone else too. :-)
